name: Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.15"

      - name: Install and test
        run: |
          npm install pnpm -g
          pnpm install

      - name: Build
        run: pnpm release

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@2.29
        with:
          branch: gh-pages
          folder: public
          clean: true
